### ISSUE TITLE
Problems during compilation

### ISSUE THREAD

**Issue by sysadmincaos** [natefoo/slurm-drmaa#16]
Hi,
I'm trying to compile slurm-drmaa-1.2.0-dev.deca826 for SLURM 17-11.5 and I'm getting errors during "configure" step. 
I'm executing "./configure --prefix=/tmp/test-slurm-drmaa --with-slurm-inc=/soft/slurm-17.11.5/include/slurm/ --with-slurm-lib=/soft/slurm-17.11.5/lib/" (my SLURM installation is installed in a NFS folder called /soft") and error is "SLURM libraries/headers not found; add --with-slurm-inc and --with-slurm-lib with appropriate locations."

Could you help me?

Thanks.

**Comment by jvanbraekel** [comment]
Hello,

I got the same error, using SLURM 17.11.2 when both libraries and headers files where present but the libslurmdb sources were missings.  On my Ubuntu distribution slurm source and slurmdb sources are part of two differents pakages :  libslurm-dev and libslurmdb-dev namely.  Installing the last one have fix the issue. Maybe that can help.

**Comment by sysadmincaos** [comment]
Hello,

Finally, I solved it by following step-by-step this procedure:
        curl -#o slurm-drmaa-1.0.7.tar.gz http://apps.man.poznan.pl/trac/slurm-drmaa/downloads/9
        tar -xf slurm-drmaa-1.0.7.tar.gz
        cd slurm-drmaa-1.0.7
        p=$(which srun)
        p=${p%/bin/srun}/lib:$LD_LIBRARY_PATH
        export LD_LIBRARY_PATH="$p"
        ./configure #CFLAGS="-g -O0"    -->  aquí, antes del #CFLAGS, le meto el --prefix que yo quiera
        make
        make install
        # rm -r slurm-drmaa*
        # Make the config file writeable by group_galaxy:
        sudo touch /etc/slurm_drmaa.conf
        sudo cp /etc/slurm_drmaa.conf /etc/slurm_drmaa.conf.original
        sudo chown :group_galaxy /etc/slurm_drmaa.conf
        sudo chmod g+w /etc/slurm_drmaa.conf
        # Test the drmaa-run binary by submitting a small job:
        export DRMAA_LIBRARY_PATH=/usr/local/lib/libdrmaa.so
        echo 'echo "Test executed on host $(hostname) by user $USER"' > test.drmaa
        drmaa-run bash test.drmaa


Change versions for your convenience and copy new generated files to your SLURM lib and include folders.
