### ISSUE TITLE
TRES slurm config settings cause errors

### ISSUE THREAD

**Issue by fangpingmu** [natefoo/slurm-drmaa#20]
drmaa-run bash test.drmaa
drmaa-run: error: _parse_next_key: Parsing error at unrecognized key: PriorityWeightTRES
drmaa-run: error: Parse error in file /etc/slurm/slurm.conf line 131: "PriorityWeightTRES=CPU=1000,Mem=2000 "
drmaa-run: error: _parse_next_key: Parsing error at unrecognized key: AccountingStorageTRES
drmaa-run: error: Parse error in file /etc/slurm/slurm.conf line 186: "AccountingStorageTRES=gres/gpu,gres/mic,gres/nvme"
drmaa-run: error: Parsing error at unrecognized key: TresBillingWeights
drmaa-run: error: Parse error in file /etc/slurm/slurm.conf line 196: " TresBillingWeights="CPU=1.0,Mem=0.127G""
drmaa-run: error: Unable to establish controller machine
Segmentation fault

**Comment by natefoo** [comment]
What version of slurm-drmaa are you using? This should be fixed as of deca82632d2af686193e101127b02bdc47f7484f (which is on the Releases tab as a development release).

**Comment by fangpingmu** [comment]
The issue is solved. The slurm-drmaa links to /usr/lib instead of /usr/lib64.
