### ISSUE TITLE
Missing sources in 1.2.0-dev.deca826 release

### ISSUE THREAD

**Issue by vanzod** [natefoo/slurm-drmaa#21]
In both source archives for the `1.2.0-dev.deca826` release the `drmaa_utils` directory is empty.

**Comment by natefoo** [comment]
Use `slurm-drmaa-1.2.0-dev.deca826.tar.gz`. The other two are automatically added by Github and are just automatically generated tarballs of the git tag. The tarball I reference is a distribution tarball. Github does not give me a way to disable these.
