### ISSUE TITLE
DRMAA on Galaxy Repo does not work

### ISSUE THREAD

**Issue by lwj5** [natefoo/slurm-drmaa#24]
https://depot.galaxyproject.org/yum/package/slurm/18.08/7/x86_64/

The DRMAA rpm is breaking as it is not meant for the slurm version.
The slurm rpm in the repo provides .so.33 and drmaa in this repo requires .so.31

```
Error: Package: slurm-drmaa-1.1.0-1.el7.x86_64 (slurm-18.08)
Requires: libslurm.so.31()(64bit)
Error: Package: slurm-drmaa-1.1.0-1.el7.x86_64 (slurm-18.08)
Requires: libslurmdb.so.31()(64bit)
You could try using --skip-broken to work around the problem
```

Do you have access to this?

**Comment by tdudgeon** [comment]
I also raised the same issue here:
https://github.com/galaxyproject/ansible-slurm/issues/3

**Comment by lwj5** [comment]
@tdudgeon I also raised the issue here: https://help.galaxyproject.org/t/fix-yum-repo-drmaa-for-slurm-18-08/1213

Looks like @natefoo will be fixing it from his replies.

**Comment by natefoo** [comment]
This should be fixed now, sorry for the delay.

**Comment by tdudgeon** [comment]
Confirmed. The updated DRMAA RPMs install for me fine now (on Centos7).
