### ISSUE TITLE
Slurm-drmaa 1.1.2 binary (RPM) installation issue with slurm-19.05.8-1

### ISSUE THREAD

**Issue by manish-nuance** [natefoo/slurm-drmaa#50]
I'm trying to install slurm-drmaa version 1.1.2 alongwith slurm version 19.05.8-1 on CentOS-7.9 machine.  It throws the package dependency issue and requires.. libslurm.so.31()(64bit) and libslurmdb.so.31()(64bit) libraries.. Whereas, slurm-19.05.8-1 provides the library libslurm.so.34 .

[root@test-vm111 ~]# cat /etc/redhat-release
CentOS Linux release 7.9.2009 (Core)

**Installed slurm packages..**
[root@test-vm111 yum.repos.d]# rpm -qa | grep ^slurm | sort
slurm-19.05.8-1.el7.x86_64
slurm-contribs-19.05.8-1.el7.x86_64
slurm-devel-19.05.8-1.el7.x86_64
slurm-example-configs-19.05.8-1.el7.x86_64
slurm-libpmi-19.05.8-1.el7.x86_64
slurm-openlava-19.05.8-1.el7.x86_64
slurm-pam_slurm-19.05.8-1.el7.x86_64
slurm-perlapi-19.05.8-1.el7.x86_64
slurm-slurmctld-19.05.8-1.el7.x86_64
slurm-slurmd-19.05.8-1.el7.x86_64
slurm-slurmdbd-19.05.8-1.el7.x86_64
slurm-torque-19.05.8-1.el7.x86_64

**Issue with slurm-drmaa 1.1.2 installation**
[root@test-vm111 yum.repos.d]# yum install slurm-drmaa
Loaded plugins: langpacks, nvidia
Resolving Dependencies
--> Running transaction check
---> Package slurm-drmaa.x86_64 0:1.1.2-1.el7 will be installed
--> Processing Dependency: libslurmdb.so.31()(64bit) for package: slurm-drmaa-1.1.2-1.el7.x86_64
--> Processing Dependency: libslurm.so.31()(64bit) for package: slurm-drmaa-1.1.2-1.el7.x86_64
--> Finished Dependency Resolution
Error: Package: slurm-drmaa-1.1.2-1.el7.x86_64 (slurm-19.05)
           Requires: libslurmdb.so.31()(64bit)
Error: Package: slurm-drmaa-1.1.2-1.el7.x86_64 (slurm-19.05)
           Requires: libslurm.so.31()(64bit)
 You could try using --skip-broken to work around the problem
 You could try running: rpm -Va --nofiles --nodigest

**libslurm.so library available in  machine**
[root@test-vm111 ~]# locate libslurm.so
/usr/lib64/libslurm.so
/usr/lib64/libslurm.so.34
/usr/lib64/libslurm.so.34.0.0  

[root@test-vm111 yum.repos.d]# rpm -qf /usr/lib64/libslurm.so.34
slurm-19.05.8-1.el7.x86_64

Anyone can look into the issue?

**Comment by natefoo** [comment]
Assuming this is working now, please reply if not.
