### ISSUE TITLE
Galaxy Project Depot certificate expired

### ISSUE THREAD

**Issue by aknijn** [natefoo/slurm-drmaa#55]
The Galaxy Project Depot certificate has expired today:

/etc/apt/trusted.gpg
--------------------
pub   rsa4096 2014-09-09 [SC] [expired: 2021-07-29]
      4AAF 9274 AC74 7FFB 1627  6F99 5262 6447 751B 835F
uid           [ expired] Nathan Coraor <nate@bx.psu.edu>
uid           [ expired] Nathan Coraor <nate@galaxyproject.org>

**Comment by natefoo** [comment]
I have updated my key expiration and pushed it to keyserver.ubuntu.com and pgp.mit.edu, so you should be able to reimport it. Please let me know if this doesn't work for you.

**Comment by aknijn** [comment]
It worked great! Thank you!
