### ISSUE TITLE
Galaxy apt debian repository access

### ISSUE THREAD

**Issue by bvalot** [natefoo/slurm-drmaa#71]
Hello.

I try to add the galaxy debian repository. But, the OpenPGP keys is not found because  the server sks-keyservers.net is down.

`galaxy:~$ sudo apt-key adv --keyserver hkp://pool.sks-keyservers.net --recv-keys 18381AC8832160AF 
Executing: /tmp/apt-key-gpghome.tn1yujkHtK/gpg.1.sh --keyserver hkp://pool.sks-keyservers.net --recv-keys 18381AC8832160AF
gpg: échec de réception depuis le serveur de clefs : Server indicated a failure`

Can we obtained this keys otherwise?

**Comment by natefoo** [comment]
sks-servers.net is dead, you can use `keyserver.ubuntu.com`, which seems to be one of the few remaining operational public PGP keyservers.
