### ISSUE TITLE
slurm-drmaa for Ubuntu Jammy

### ISSUE THREAD

**Issue by hexylena** [natefoo/slurm-drmaa#73]
https://launchpad.net/~natefoo/+archive/ubuntu/slurm-drmaa releases only go up to 20.04, 22.04 support would be useful xref https://help.galaxyproject.org/t/cluster-configuration-slurm-drmaa-jammy-release-file-missing/8981

**Comment by nsoranzo** [comment]
This would also be helpful for Pulsar: CI builds are starting to fail now that GitHub Workflows are moving to Ubuntu 22.04 .

**Comment by natefoo** [comment]
Done!
