### ISSUE TITLE
dependency libslurm36 missing for debian bookworm

### ISSUE THREAD

**Issue by aknijn** [natefoo/slurm-drmaa#80]
Trying to install slurm-drmaa on debian bookworm the following error occurs:
apt install slurm-drmaa1
Reading package lists... Done
Building dependency tree... Done
Reading state information... Done
Some packages could not be installed. This may mean that you have
requested an impossible situation or if you are using the unstable
distribution that some required packages have not yet been created
or been moved out of Incoming.
The following information may help to resolve the situation:

The following packages have unmet dependencies:
 slurm-drmaa1 : Depends: libslurm36 (>= 20.11.2) but it is not installable

**Comment by aknijn** [comment]
Bookworm has libslurm38 (22.05.8-4)

**Comment by natefoo** [comment]
Sorry, I have barely been able to get aptly working properly, so updating the apt repo for it might not happen but I have added the `.deb` to the downloads section on the release page.

**Comment by aknijn** [comment]
No problem, the deb worked perfectly. Many thanks!
