### ISSUE TITLE
Galaxy Project Depot certificate expired

### ISSUE THREAD

**Issue by aknijn** [natefoo/slurm-drmaa#81]
The certificate has expired:

sig  sig  52626447751b835f 2021-08-16T20:50:23Z 2023-08-16T20:50:17Z

**Comment by aknijn** [comment]
Thank you

**Comment by natefoo** [comment]
This is for the APT repo? Should be fixed now I believe.

**Comment by aknijn** [comment]
Yes, it was fixed three weeks ago. Thanks again!
